version: '3.9'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'iot-auction-box'
      MYSQL_USER: 'administrator'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
    name: mysql-db
